humanizer_app/blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.PostList.as_view(), name="blogs"),
     path("<slug:slug>/", views.article, name="article"),
   
]

humanizer_app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import CustomPasswordResetView, signup_view,resend_email_confirmation
from django.conf.urls import handler404
from blog.views import article
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'front.views.view_404'

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('accounts/password/reset/', CustomPasswordResetView.as_view(), name='account_reset_password'),
    path('accounts/signup/', signup_view, name='account_signup'),
    path('accounts/', include('allauth.urls')),
    path('accounts/password/reset/done/', CustomPasswordResetView.as_view(), name='account_reset_password_done'),
    path('accounts/resend-email-confirmation/signup/', resend_email_confirmation, name='resend_email_confirmation'),
    path("dashboard/", include("dashboard.urls")),
    path("payments/", include("payments.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path("blog/", include("blog.urls")),
    
    path("", include("front.urls")),


    # path("users/", include("users.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

humanizer_app/dashboard/urls.py
from django.urls import path
from .views import index, profile, edit_profile, documents, document_detail,logout_view, text_editor, generate_text, extend_text_view, style_view, styles_list, style_detail,update_basic_info, update_analyze_data

urlpatterns = [
    path('', index, name='dashboard'),
    path('profile/', profile, name='profile'),
    path("profile/edit/", edit_profile, name="edit_profile"),
    path("documents/", documents, name="documents"),
    path('documents/<str:document_id>/', document_detail, name='document_detail_api'),
    path("logout/", logout_view, name="logout"),
    path("generate_content/", text_editor, name='editor'),
    path("generate_text/", generate_text, name='generate_text'),
    path("extend_text_view/", extend_text_view, name='extend_text'),
    path("style/add/",  style_view, name='add_style'),
    path("style/list/", styles_list, name='styles_list'),
    path("style/<str:style_id>/", style_detail, name='style_detail'),
    path("update_basic_info/<int:style_id>/", update_basic_info, name='update_basic_info'),
    path("update_analyze_data/<int:style_id>/", update_analyze_data, name='update_analyze_data'),
    



]

humanizer_app/dashboard/models.py
from django.db import models
from users.models import UserModel
# Create your models here.
import uuid 

from django_ckeditor_5.fields import CKEditor5Field
 # Import your Celery task

class Documents(models.Model):
    input_text = models.TextField()
    output_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    words_used = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    purpose = models.CharField(max_length=100, null=True, blank=True)
    level = models.CharField(max_length=100, null=True, blank=True)
    readibility = models.CharField(max_length=100, null=True, blank=True)
    document_id = models.UUIDField(default = uuid.uuid4, editable = False)
    model = models.CharField(max_length=100, null=True, blank=True)


class EmailCampaign(models.Model):
    MONTHLY = 'monthly'
    YEARLY = 'yearly'
    ENTERPRISE = 'enterprise'
    FREE = 'free'
    ALL = 'all'

    PLAN_CHOICES = [
        (MONTHLY, 'Monthly'),
        (YEARLY, 'Yearly'),
        (ENTERPRISE, 'Enterprise'),
        (FREE, 'Free'),
        (ALL, 'all')
    ]
    subject = models.CharField(max_length=255)
    message = CKEditor5Field()
    sent_at = models.DateTimeField(auto_now_add=True)
    recipients = models.JSONField(null=True, blank=True)  # Store the list of user IDs to whom the email will be sent
    completed = models.BooleanField(default=False)
    subscrioption_type = models.CharField(max_length=10, choices=PLAN_CHOICES, null=True,)

    def __str__(self):
        return self.subject
    
    def save(self, *args, **kwargs):
        from .tasks import send_email_batch 
        is_new = self._state.adding
        if is_new:
            # Determine and set recipients based on subscription type
            if self.subscrioption_type == self.ALL:
                recipient_users = UserModel.objects.all()
            else:
                recipient_users = UserModel.objects.filter(subscription__plan_type=self.subscrioption_type)

            self.recipients = list(recipient_users.values_list('id', flat=True))
        
        super().save(*args, **kwargs)

        if is_new:
            # Trigger Celery task after the campaign is saved
            send_email_batch.delay(self.id)






class WritingStyle(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)  # Description of the style
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  # Track when the style was last updated
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    analyze = models.JSONField(null=True, blank=True)
    status = models.CharField(max_length=50, default='active')  # Status of the writing style

class StylePurchase(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    purchased_at = models.DateTimeField(auto_now_add=True)  # Timestamp of purchase
    transaction_id = models.CharField(max_length=200)  # ID from your payment gateway
    quantity = models.PositiveIntegerField(default=1)  # Quantity of the style purchased
    purchased_price = models.DecimalField(max_digits=10, decimal_places=2)  # Price at which the style was purchased
    used_count = models.PositiveIntegerField(default=0)  # Track the number of times the style was used

humanizer_app/dashboard/forms.py
from django import forms
from django.core.exceptions import ValidationError

class WritingStyleForm(forms.Form):
    name = forms.CharField(label='Style Name', max_length=100)
    description = forms.CharField(label='Description', widget=forms.Textarea, required=False)
    text = forms.CharField(label='Text', widget=forms.Textarea)  # Assuming 'text' is a required field
    def clean_text(self):
        text = self.cleaned_data.get('text', '')

        # Check if the text is longer than 20,000 characters
        if len(text) > 20000:
            raise ValidationError('Text cannot be more than 20,000 characters.')

        return text

humanizer_app/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from payments.models import Subscription, WordCountTracker
from .models import Documents, WritingStyle, StylePurchase
from django.core.paginator import Paginator
from django.db.models import Avg
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, Http404
import uuid
import stripe
from django.conf import settings
import datetime
from django.contrib.auth import logout
from common.content_writer import generate_content, extend_text
import json
from common.style_ai import anaylze_style
from .forms import WritingStyleForm
from django.contrib import messages
from dashboard.tasks import analyse_text_task
stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.
def get_dashboard_data(user):
    data = {'subscription_name': 'No Active Subscription', 'available_words': 0, 'used_words': 0, 'used_percentage': 0}
    
    active_subscription = Subscription.objects.filter(user=user, is_active=True).first()
    if active_subscription:
        data['subscription_name'] = active_subscription.plan_type.capitalize()
        data["subscrioption_price"] = active_subscription.price_in_cents / 100
        data["subscrioption_id"] =  active_subscription.stripe_subscription_id
        
        try:
            data["next_due_date"] = active_subscription.end_date.date
        except: 
          
            data["next_due_date"] = active_subscription.end_date
    word_count_tracker = WordCountTracker.objects.filter(subscription__user=user).last()
    documents_count = Documents.objects.filter(user=user).count()
    average_words_per_document = Documents.objects.filter(user=user).aggregate(average_words=Avg('words_used'))['average_words']

# You might want to handle the case where there are no documents
    if average_words_per_document is None:
        average_words_per_document = 0
    
    if word_count_tracker:
        data['available_words'] = word_count_tracker.words_remaining
        data['words_purchased'] = word_count_tracker.words_purchased
        data['used_words'] = word_count_tracker.words_used
        data["documents_count"] = documents_count
        data["average_words_per_document"] = round(average_words_per_document)
        if word_count_tracker.words_purchased > 0:
            data['used_percentage'] = (word_count_tracker.words_used / word_count_tracker.words_purchased) * 100

    return data

@login_required
def index(request):
    context = get_dashboard_data(request.user)
    recent_documents = Documents.objects.filter(user=request.user).order_by('-created_at')[:5]
    if recent_documents.count() > 0:
        context["recent_documents"] = recent_documents
    else:
        context["recent_documents"] = None
    context["recent_documents"] = recent_documents
    return render(request, "dashboard/dashboard.html", context)

def get_stripe_customer_id_by_email(user_email):
    customers = stripe.Customer.list(email=user_email).auto_paging_iter()
    for customer in customers:
        # Assuming one email is associated with only one customer
        return customer.id
    return None

def get_formated_invoices(customer_id):
    formatted_invoices = []
    invoices = stripe.Invoice.list(customer=customer_id)
    for invoice in invoices.get('data', []):
        # Subscription Name
        subscription_name = invoice['lines']['data'][0]['description'] if invoice['lines']['data'] else 'N/A'

        # Payment Date (convert from Unix timestamp to human-readable date)
        payment_date = datetime.datetime.fromtimestamp(invoice['created']).strftime('%Y-%m-%d')

        # Total (convert from smallest currency unit to standard format, e.g., cents to dollars)
        total = invoice['total'] / 100.0

        # Status
        status = invoice['status']

        formatted_invoices.append({
            'subscription_name': subscription_name.replace("1 ×", ""),
            'payment_date': payment_date,
            'total': total,
            'status': status,
            'invoice_pdf': invoice['invoice_pdf'],

        })
    return formatted_invoices

@login_required
def profile(request):
    user_email = request.user.email
    customer_id = get_stripe_customer_id_by_email(user_email)
    
    if customer_id:
        invoices = get_formated_invoices(customer_id)
        # Or use stripe.Charge.list(customer=customer_id) if you want to list charges
    else:
        invoices = []
    context = get_dashboard_data(request.user)
    context["invoices"] = invoices
    context["subscription_name_period"] = context["subscription_name"].replace("ly", "")
    return render(request, "dashboard/profile.html", context=context)

@login_required
def edit_profile(request):
    context = get_dashboard_data(request.user)
    if request.method == 'POST':
        fullname = request.POST.get('fullname')
        country = request.POST.get('country')
        is_checked = 'check_box' in request.POST

        if is_checked:
            checked = True
        else:
            checked = False
        user = request.user
        user.fullname = fullname
        user.country = country
        user.does_email_receive = checked
        user.save()
        return redirect('profile')
    
    return render(request, "dashboard/edit_profile.html", context=context)


@login_required
def documents(request):
    # Fetch search query and sort parameters from the request
    search_query = request.GET.get('search', '')
    sort_by = request.GET.get('sort', '-created_at')  # Default sort is by created_at

    # Filter and sort documents based on the search query and sort parameter
    documents = Documents.objects.filter(
        user=request.user, 
        input_text__icontains=search_query  # Assuming you are searching by document name
    ).order_by(sort_by)

    # Add Pagination
    paginator = Paginator(documents, 15)  # Show 10 documents per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'documents': page_obj
    }
    return render(request, "dashboard/documents.html", context=context)


@login_required
def document_detail(request, document_id):
    try:
        # Make sure we have a valid UUID
        uuid.UUID(document_id)
    except ValueError:
        raise Http404("Invalid document ID format.")

    # Retrieve the document, making sure it exists and belongs to the current user
    try:
        document = Documents.objects.get(document_id=document_id, user=request.user)
    except Documents.DoesNotExist:
        raise Http404("Document not found.")

    # If the user is not the owner of the document, raise PermissionDenied
    if document.user != request.user:
        raise PermissionDenied

    # Prepare the data to be returned as JSON
    data = {
        'input_text': document.input_text,
        'output_text': document.output_text,
        'created_at': document.created_at.isoformat(),
        'words_used': document.words_used,
        'purpose': document.purpose,
        'level': document.level,
        'readibility': document.readibility,
        'document_id': str(document.document_id),  # Convert UUID to string
    }

    return JsonResponse(data)


@login_required
def logout_view(request):
    logout(request)
    return redirect('index')


@login_required
def text_editor(request):
    return render(request, 'dashboard/editor.html')


@login_required
def generate_text(request):
    if request.method == 'POST':
        # Parse JSON data from the request body
        data = json.loads(request.body)
        topic = data.get('topic')
        tone = data.get('tone')
        keywords = data.get('keywords')
        language = data.get('language')
        content_type = data.get('content_type')
        min_words_count = data.get('min_words_count')
        max_words_count = data.get('max_words_count')
        user = request.user
        document_id = uuid.uuid4()
        # Call your custom text generation function
        subscrioption = Subscription.objects.filter(user=request.user).last()

        
        if  subscrioption.is_active == False or subscrioption.plan_type == Subscription.FREE:
            return JsonResponse({"error": "Upgrade required"}, status=400)
        result = generate_content(content_type, topic, tone, keywords, language)
       
        
        # Return the result as JSON
        return JsonResponse({'result': result, 'document_id': str(document_id)})
    


@login_required
def extend_text_view(request):
    if request.method == 'POST':
        # Parse JSON data from the request body
        data = json.loads(request.body)
        text = data.get('text')
        tone = data.get('tone')
        keywords = data.get('keywords')
        language = data.get('language')
        min_words_count = data.get('min_words_count')
        max_words_count = data.get('max_words_count')
       
        subscrioption = Subscription.objects.filter(user=request.user).last()

        
        if  subscrioption.is_active == False or subscrioption.plan_type == Subscription.FREE:
            return JsonResponse({"error": "Upgrade required"}, status=400)

        # Call your custom text generation function
        result = extend_text(text, tone, keywords, language, max_words_count, min_words_count)
   
        
        return JsonResponse({'result': result})
    


def style_view(request):
    if request.method == "POST":
        form = WritingStyleForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            text = form.cleaned_data['text']
            user = request.user
            created_style = WritingStyle.objects.create(name=name, description=description, user=user, status='processing')
            analyse_text_task.delay(text, name, description, user.id, created_style.id)

humanizer_app/templates/dashboard/edit_profile.html
{% extends 'dashboard/main.html' %}

{% block meta_tags %}
<title>Edit Profile - AI Humanize</title>
<meta name="description"
    content="Update your profile settings on AI Humanize. Personalize your account information to enhance your experience with our AI text humanizing services." />
<meta property="og:title" content="Edit Profile - AI Humanize" />
<meta property="og:description"
    content="Personalize your AI Humanize experience. Update your profile information and settings to tailor our services to your needs." />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://aihumanize.com/" />
{% endblock %}
{% block content %}

<div class="container-xl">
    <div class="nk-content-inner">
        <div class="nk-content-body">
            <div class="nk-block-head nk-page-head">
                <div class="nk-block-head-between">
                    <div class="nk-block-head-content">
                        <h2 class="display-6">Edit Profile</h2>
                    </div>
                </div>
            </div><!-- .nk-page-head -->
            <div class="nk-block">

                <div class="card shadown-none">
                    <div class="card-body">
                        <form action="{% url 'edit_profile' %}" class="form" method="post"> {% csrf_token %}
                        <div class="row g-3 gx-gs">
                            
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="fullnameId" class="form-label">Full Name</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" id="fullnameId"
                                            placeholder="Enter Full name here" name="fullname" {% if request.user.fullname != None %} value="{{request.user.fullname}}" {% endif %}>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="countryID" class="form-label">Country</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" id="countryID"
                                            placeholder="Enter Country here" {% if request.user.country != None %}
                                            value="{{request.user.country}}" {% endif %} name="country">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="check_box" id="flexCheckChecked" {% if request.user.does_email_receive == True %} checked {%endif%}>
                                    <label class="form-check-label" for="flexCheckChecked"> I would like to receive updates and news via email.
                                    </label>
                                </div>
                            </div>
                            
                            <div class="col-md-12">
                                <button class="btn btn-outline-primary" type="submit">Update</button>
                            </div>
                       
                        </div>
                    </form>
                    </div><!-- .card-body -->
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

humanizer_app/templates/dashboard/style.html
{% extends 'dashboard/main.html' %}
{% load static %}
{% block meta_tags %}
<title>Create Your Writing Style - AI Humanize</title>
<meta name="description"
    content="Craft your unique writing style with AI Humanize. Tailor your style to fit your voice and preferences for a personalized writing experience." />
<meta property="og:title" content="Create Your Writing Style - AI Humanize" />
<meta property="og:description"
    content="Unlock the full potential of your writing with personalized styles created by AI Humanize. Start creating a style that truly reflects your voice." />
<meta property="og:type" content="website" />

<!-- Replace with an actual image URL -->

{% endblock %}

{% block content %}


<div class="container-xl">
    <div class="nk-content-inner">
        <div class="nk-content-body">
            <div class="nk-block-head nk-page-head">
                <div class="nk-block-head-between">
                    <div class="nk-block-head-content">
                        <h2 class="display-6">Add Writing Style</h2>
                    </div>
                </div>
            </div><!-- .nk-page-head -->
            <div class="nk-block">

                <div class="card shadown-none">
                    <div class="card-body">
                    <form action="{% url 'add_style' %}" class="form" method="post">
                        {% csrf_token %}
                        <div class="row g-3 gx-gs">
                            <!-- Name Field -->
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="form-control-wrap">
                                        <label for="id_name">{{ form.name.label }}</label>
                                        <input type="text" id="id_name" name="{{ form.name.html_name }}" class="form-control"
                                            value="{{ form.name.value|default_if_none:'' }}">
                                        {% if form.name.errors %}
                                        <div class="text-danger">{{ form.name.errors }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <!-- Description Field -->
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="form-control-wrap">
                                        <label for="id_description">{{ form.description.label }}</label>
                                        <textarea id="id_description" name="{{ form.description.html_name }}" 
                                            class="form-control">{{ form.description.value|default_if_none:'' }}</textarea>
                                        {% if form.description.errors %}
                                        <div class="text-danger">{{ form.description.errors }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <!-- Text Field -->
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="form-control-wrap">
                                        <label for="id_text">{{ form.text.label }}</label>
                                        <textarea id="id_text" name="{{ form.text.html_name }}" class="form-control" rows="10"
                                            placeholder="Paste text here or use the 'Upload File' button to analyze a document">{{ form.text.value|default_if_none:'' }}</textarea>
                                        {% if form.text.errors %}
                                        <div class="text-danger">{{ form.text.errors }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                
                                    <strong>Characters Cound: <span class="text-secondary" id="chars_count">0</span></strong>
                                   
                            </div>
                            <div id="char_limit_error" class="text-danger" style="display: none;">
                                Currently, we also support up to 20,000 characters. We are working on increasing this limit.
                            </div>
                            <div class="col-md-12">
                                <div class="file ">
                                    <label for="input-file">
                                        <i class="p-1"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                                                <path d="M0 0h24v24H0z" fill="none"></path>
                                                <path
                                                    d="M19.35 10.04C18.67 6.59 15.64 4 12 4 9.11 4 6.6 5.64 5.35 8.04 2.34 8.36 0 10.91 0 14c0 3.31 2.69 6 6 6h13c2.76 0 5-2.24 5-5 0-2.64-2.05-4.78-4.65-4.96zM19 18H6c-2.21 0-4-1.79-4-4s1.79-4 4-4h.71C7.37 7.69 9.48 6 12 6c3.04 0 5.5 2.46 5.5 5.5v.5H19c1.66 0 3 1.34 3 3s-1.34 3-3 3z">
                                                </path>
                                            </svg></i>Upload File
                                    </label>
                                    <input id="input-file" class="btn btn-lg" type="file">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-primary">Start Training</button>
                            </div>
                            </div>
                            <!-- Other Fields -->
                            <!-- ... -->
                        </div>
                    </form>

                    </div><!-- .card-body -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.7.570/pdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.6.0/mammoth.browser.min.js"></script>
<script>






    document.getElementById('input-file').addEventListener('change', function (event) {
            const file = event.target.files[0];
            if (!file) {
                return;
            }

            let inputTextArea = document.getElementById('input-text');
            
            if (file.type === 'application/pdf') {
                // Handle PDF file
                const fileReader = new FileReader();
                fileReader.onload = function () {
                    const typedarray = new Uint8Array(this.result);

                    pdfjsLib.getDocument(typedarray).promise.then(pdf => {
                        let text = '';
                        for (let i = 1; i <= pdf.numPages; i++) {
                            pdf.getPage(i).then(page => {
                                page.getTextContent().then(content => {
                                    content.items.forEach(item => {
                                        text += item.str + ' ';
                                    });

                                    if (i === pdf.numPages) {
                                        // Set the textarea value and hide the paste button div

                                       
                                        inputTextArea.value = text;
                                    }
                                });
                            });
                        }
                    });
                };
                fileReader.readAsArrayBuffer(file);
            } else if (file.type === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
                // Handle Word file (.docx)
                const fileReader = new FileReader();
                fileReader.onload = function (event) {
                    const arrayBuffer = event.target.result;

                    mammoth.extractRawText({ arrayBuffer: arrayBuffer })
                        .then(result => {
                    
                            inputTextArea.value = result.value;
                        })
                        .catch(err => {
                            console.error('Error reading .docx file:', err);
                        });
                };
                fileReader.readAsArrayBuffer(file);
            } else {
                inputTextArea.value = 'Unsupported file type.';
            }
        });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        let inputText = document.getElementById('id_text');
        var charCountSpan = document.getElementById('chars_count');
        var charLimitError = document.getElementById('char_limit_error');

        inputText.addEventListener('input', function () {
            var charCount = inputText.value.length;
            charCountSpan.textContent = charCount;

            if (charCount > 20000) {
                charLimitError.style.display = 'block';
            } else {
                charLimitError.style.display = 'none';
            }
        });
    });
</script>
{% endblock %}